name: stoream-website

on:
  push:
    branches:
      - dev

jobs:
  pages:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./stoream-website

    strategy:
      matrix:
        dotnet-version: [ '9.0' ]
        node-version: [20]

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
        
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: ./stoream-website/pnpm-lock.yaml
      
      - name: Install dependencies
        run: dotnet restore && dotnet tool restore && pnpm install
      
      - name: Build
        run: dotnet fable && pnpm exec vite build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist