name: Test Rust project
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./stoream-webui

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]

    steps:
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Run build
      run: cargo build --release
    - name: Run test
      run: cargo test --verbose