name: stoream-engine

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: [v*]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [3.3.1]
        java: [graal_22.3.0@17]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java (temurin@8)
        if: matrix.java == 'temurin@8'
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: sbt

      - name: Setup GraalVM (graal_22.3.0@17)
        if: matrix.java == 'graal_22.3.0@17'
        uses: graalvm/setup-graalvm@v1
        with:
          version: 22.3.0
          java-version: 17
          components: native-image
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: sbt

      - name: Build
        run: sbt compile
        working-directory: ./stoream-engine

      - name: Test
        run: sbt test
        working-directory: ./stoream-engine